language: python
os: linux
sudo: required
dist: xenial

python:
    - 3.7
addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - libopenmpi-dev
            - openmpi-bin
env:
    - CAPUT_SKYFIELD_PATH=/home/travis OMP_NUM_THREADS=1

install:
    - "pip install -U future numpy cython pytest pydocstyle black"
    - "pip install -r requirements.txt"
    - "pip install -e ."
script:
    - black --check .

    # TODO: add the rest of the project to this test
    - pydocstyle --convention=numpy tests/test_simplepolarizationtelescope.py

    - "cd tests/; pytest -svv"
